require: rubocop-performance
inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - Gemfile
    - Gemfile.lock
    - spec/spec_helper.rb
Metrics/LineLength:
  Max: 150
  IgnoredPatterns: ['(\A|\s)#']
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/BlockLength:
  Max: 40
  Exclude:
    - "**/*_spec.rb"
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Max: 50
